# Generated by Django 4.0.5 on 2023-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_join',
            field=models.ManyToManyField(blank=True, related_name='students_in_class', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_join',
            field=models.ManyToManyField(blank=True, related_name='teacher_in_class', to='classes.classroom'),
        ),
    ]
