# Generated by Django 4.0.5 on 2023-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_post_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
