# Generated by Django 4.0.5 on 2023-08-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='school_year',
            field=models.PositiveIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='classroom',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
