# Generated by Django 4.0.5 on 2023-08-31 06:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0006_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'classroom')},
        ),
    ]
